### ISSUE TITLE
Calling setState in ComponentDidMount

### ISSUE THREAD

**Issue by Becherman** [reactpatterns/reactpatterns#26]
Hi, Banlong! I considered your first pattern of async operations in components and i have some questions about it. You are offering to call setState directly in ComponentDidMount, but [official documentation](https://reactjs.org/docs/react-component.html#componentdidmount) say's that invoking setState will produce unnecessary components rerender and can lead to performance issues. In addition to documentation, all developers who use eslint-plugin-react will have an error message about [this](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-mount-set-state.md) rule? Could you explain why you chose this approach and will it not be confusing other developers?

**Comment by Bunlong** [comment]
Hi, @Becherman I've gone through your comment and I got your points. Well, React official document say calling setState() directly in componentDidMount method will trigger an extra rendering and causes performance issues. But calling an ajax method or async request (and THEN calling setState when it completes) is not the same thing as calling setState directly in componentDidMount since this function is guaranteed to be called only once it is a perfect candidate for performing any side-effect causing operations such as AJAX requests.

If you have any questions please feel free to ask me. Thanks!
